### ISSUE TITLE
请教划词Base64解密使用指南

### ISSUE THREAD

**Issue by soyadokio** [zyronon/V2Next#39]
## 问题：
“划词显示Base64解码框”功能开启后，划词没有看到相关提示/按钮等。
已经找了Github 和 Greasy Fork 上的使用说明/README 和 用户反馈，没有找到相关使用指南。

## 截图：
![image](https://github.com/zyronon/v2ex-script/assets/16408325/40b61bf3-9b96-4ca5-8441-c2ff5a4811dd)

## 控制台报错：
![image](https://github.com/zyronon/v2ex-script/assets/16408325/fc12c57d-b667-42ad-951d-4a5fb05413f3)

```
content-all.js:1  Uncaught (in promise) Error: Extension context invalidated.
    at content-all.js:1:9680
    at new Promise (<anonymous>)
    at g (content-all.js:1:9608)
    at Object.apply (content-all.js:1:7694)
    at e (content-all.js:647:6065)
(anonymous) @ content-all.js:1
g @ content-all.js:1
apply @ content-all.js:1
e @ content-all.js:647
Show 4 more frames
显示简略信息
content-all.js:1  Uncaught (in promise) Error: Extension context invalidated.
    at content-all.js:1:9680
    at new Promise (<anonymous>)
    at g (content-all.js:1:9608)
    at Object.apply (content-all.js:1:7694)
    at Y3.onCanInsert (content-all.js:647:6261)
    at Y3.cn.leading (content-all.js:274:93881)
    at p (content-all.js:274:73378)
    at f (content-all.js:274:73436)
    at S (content-all.js:274:73871)
    at Y3.onSelectionChagne.cn.leading (content-all.js:274:94203)
(anonymous) @ content-all.js:1
g @ content-all.js:1
apply @ content-all.js:1
(anonymous) @ content-all.js:647
Y3.cn.leading @ content-all.js:274
p @ content-all.js:274
f @ content-all.js:274
S @ content-all.js:274
Y3.onSelectionChagne.cn.leading @ content-all.js:274
p @ content-all.js:274
f @ content-all.js:274
S @ content-all.js:274
Show 12 more frames
显示简略信息
content-all.js:1  Uncaught (in promise) Error: Extension context invalidated.
    at content-all.js:1:9680
    at new Promise (<anonymous>)
    at g (content-all.js:1:9608)
    at Object.apply (content-all.js:1:7694)
    at Y3.onCanInsert (content-all.js:647:6261)
    at Y3.cn.leading (content-all.js:274:93881)
    at p (content-all.js:274:73378)
    at f (content-all.js:274:73436)
    at S (content-all.js:274:73871)
    at Y3.onSelectionChagne.cn.leading (content-all.js:274:94203)
(anonymous) @ content-all.js:1
g @ content-all.js:1
apply @ content-all.js:1
(anonymous) @ content-all.js:647
Y3.cn.leading @ content-all.js:274
p @ content-all.js:274
f @ content-all.js:274
S @ content-all.js:274
Y3.onSelectionChagne.cn.leading @ content-all.js:274
p @ content-all.js:274
b @ content-all.js:274
g @ content-all.js:274
setTimeout(异步)
g @ content-all.js:274
setTimeout(异步)
g @ content-all.js:274
setTimeout(异步)
f @ content-all.js:274
S @ content-all.js:274
Show 16 more frames
显示简略信息
content.0352e950.js:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'faviconURL')
    at y (content.0352e950.js:1:97966)
    at async e._next (selection.420695b7.js:1:24961)
y @ content.0352e950.js:1
await in y(异步)
e.__tryOrUnsub @ 18.819ea6d2.js:21
e.next @ 18.819ea6d2.js:21
e._next @ 18.819ea6d2.js:21
e.next @ 18.819ea6d2.js:21
e.notifyNext @ 18.819ea6d2.js:21
e._next @ 18.819ea6d2.js:21
e.next @ 18.819ea6d2.js:21
e._next @ 18.819ea6d2.js:21
e.next @ 18.819ea6d2.js:21
e._next @ 18.819ea6d2.js:21
e.next @ 18.819ea6d2.js:21
e._next @ 18.819ea6d2.js:21
e.next @ 18.819ea6d2.js:21
e._next @ 18.819ea6d2.js:21
e.next @ 18.819ea6d2.js:21
t.observe @ 18.819ea6d2.js:21
e.dispatch @ 18.819ea6d2.js:21
e._execute @ 18.819ea6d2.js:21
e.execute @ 18.819ea6d2.js:21
e.flush @ 18.819ea6d2.js:21
setInterval(异步)
e.requestAsyncId @ 18.819ea6d2.js:21
e.schedule @ 18.819ea6d2.js:21
t.schedule @ 18.819ea6d2.js:21
e.schedule @ 18.819ea6d2.js:21
e._schedule @ 18.819ea6d2.js:21
e.scheduleNotification @ 18.819ea6d2.js:21
e._next @ 18.819ea6d2.js:21
e.next @ 18.819ea6d2.js:21
e._next @ 18.819ea6d2.js:21
e.next @ 18.819ea6d2.js:21
e._next @ 18.819ea6d2.js:21
e.next @ 18.819ea6d2.js:21
(anonymous) @ 18.819ea6d2.js:21
Show 34 more frames
显示简略信息
content-all.js:1  Uncaught (in promise) Error: Extension context invalidated.
    at content-all.js:1:9680
    at new Promise (<anonymous>)
    at g (content-all.js:1:9608)
    at Object.apply (content-all.js:1:7694)
    at Y3.onCanInsert (content-all.js:647:6261)
    at Y3.cn.leading (content-all.js:274:93881)
    at p (content-all.js:274:73378)
    at b (content-all.js:274:73669)
    at g (content-all.js:274:73608)
(anonymous) @ content-all.js:1
g @ content-all.js:1
apply @ content-all.js:1
(anonymous) @ content-all.js:647
Y3.cn.leading @ content-all.js:274
p @ content-all.js:274
b @ content-all.js:274
g @ content-all.js:274
setTimeout(异步)
g @ content-all.js:274
setTimeout(异步)
f @ content-all.js:274
S @ content-all.js:274
Y3.onSelectionChagne.cn.leading @ content-all.js:274
p @ content-all.js:274
b @ content-all.js:274
g @ content-all.js:274
setTimeout(异步)
g @ content-all.js:274
setTimeout(异步)
g @ content-all.js:274
setTimeout(异步)
f @ content-all.js:274
S @ content-all.js:274
Show 19 more frames
显示简略信息
```

**Comment by zyronon** [comment]
![image](https://github.com/zyronon/v2ex-script/assets/19986642/072b03c7-0758-4aae-b5fa-168db4e0de13)

另外，你这个界面不对，你的脚本没生效，你看你的UI和我发的图片的UI不一样。请把其他脚本关了

**Comment by soyadokio** [comment]
![image](https://github.com/zyronon/v2ex-script/assets/16408325/a56438f6-9763-4c6d-97f9-057595f0b494)

> 你这个界面不对，你的脚本没生效，你看你的UI和我发的图片的UI不一样。

我的生效了，是我手动把大半功能关闭了，所以界面上没看出来。

> 请把其他脚本关了

我尝试过把所有脚本禁用，包括uBlock origin和油猴管理器，仍旧是这种状况。
